In [1]:
#This imports the pandas, numpy libraries and datetime to timestamp the output file
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
np.random.seed(42)

In [3]:
num_patients = 1000

In [16]:
#PART I: Synthetic data creation
data = {'Patient_ID': [], 'Gender': [], 'Condition_1': [], 'Diagnosis_Date_1': [],
        'Condition_2': [], 'Diagnosis_Date_2': [], 'Condition_3': [], 'Diagnosis_Date_3': []}

In [17]:
medical_conditions = ['Diabetes', 'Hypertension', 'Asthma', 'Obesity', 'Arthritis', 'Depression', 'Migraine', 'Allergies', 'Osteoporosis', 'Anemia']

In [18]:
for patient_id in range(1, num_patients + 1):
    # Add patient ID and gender
    data['Patient_ID'].append(patient_id)
    data['Gender'].append(np.random.choice(['Male', 'Female']))

    # This generates a random number of medical conditions (at least one)
    num_conditions = np.random.randint(1, 4)
    condition_dates = [pd.Timestamp(np.random.randint(2000, 2023), np.random.randint(1, 13), np.random.randint(1, 29)) for _ in range(num_conditions)]

    # This adds a medical condition and diagnosis date
    for i in range(3):
        if i < num_conditions:
            data[f'Condition_{i+1}'].append(np.random.choice(medical_conditions))
            data[f'Diagnosis_Date_{i+1}'].append(condition_dates[i])
        else:
            data[f'Condition_{i+1}'].append(np.nan)
            data[f'Diagnosis_Date_{i+1}'].append(pd.NaT)

In [19]:
synthetic_health_data = pd.DataFrame(data)

In [20]:
synthetic_health_data.set_index('Patient_ID', inplace=True)
synthetic_health_data

,Gender,Condition_1,Diagnosis_Date_1,Condition_2,Diagnosis_Date_2,Condition_3,Diagnosis_Date_3
Patient_ID,,,,,,,
1,Female,Asthma,2008-08-25,Allergies,2014-10-08,NaN,NaT
2,Female,Obesity,2005-06-03,Anemia,2009-01-28,NaN,NaT
3,Female,Obesity,2010-12-10,Obesity,2017-07-07,NaN,NaT
4,Male,Anemia,2012-02-09,NaN,NaT,NaN,NaT
5,Female,Hypertension,2022-09-10,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...
996,Male,Hypertension,2001-08-24,Diabetes,2016-01-04,NaN,NaT
997,Male,Allergies,2018-01-02,NaN,NaT,NaN,NaT
998,Male,Allergies,2006-06-16,Migraine,2015-01-22,Hypertension,2006-04-08
999,Female,Obesity,2011-12-23,Osteoporosis,2005-02-24,NaN,NaT
1000,Female,Depression,2018-03-08,Asthma,2001-09-04,NaN,NaT

In [ ]:
#Part II: Pivot and clean